SEED_WORDS = [
    # Simple words
    {"topic": "Simple words", "en": "seldom", "ru": "редко"},
    {"topic": "Simple words", "en": "necessary", "ru": "необходимо [нессесери]"},
    {"topic": "Simple words", "en": "Fence", "ru": "забор"},
    {"topic": "Simple words", "en": "shine", "ru": "светить"},
    {"topic": "Simple words", "en": "shame", "ru": "обидно"},
    {"topic": "Simple words", "en": "lent", "ru": "одолжить"},
    {"topic": "Simple words", "en": "landscape", "ru": "пейзаж"},
    {"topic": "Simple words", "en": "essential", "ru": "важно"},
    {"topic": "Simple words", "en": "believe in", "ru": "верить во что-то"},
    {"topic": "Simple words", "en": "enough", "ru": "достаточно"},
    {"topic": "Simple words", "en": "even", "ru": "даже [ивен]"},
    {"topic": "Simple words", "en": "Jew", "ru": "евреец"},
    {"topic": "Simple words", "en": "straight", "ru": "прямо"},
    {"topic": "Simple words", "en": "deserves", "ru": "заслуживать"},
    {"topic": "Simple words", "en": "society", "ru": "общество [сосаити]"},
    {"topic": "Simple words", "en": "the effort", "ru": "усилия"},
    {"topic": "Simple words", "en": "extra", "ru": "дополнительно"},
    {"topic": "Simple words", "en": "concerned", "ru": "обеспокоенный"},
    {
        "topic": "Simple words",
        "en": "as far as i'm concerned",
        "ru": "на сколько это мое дело",
    },
    {"topic": "Simple words", "en": "special", "ru": "особенный"},
    {"topic": "Simple words", "en": "fill", "ru": "наполнить"},
    {"topic": "Simple words", "en": "starving", "ru": "голодать"},
    {"topic": "Simple words", "en": "wage", "ru": "зарплата"},
    {"topic": "Simple words", "en": "deem", "ru": "считать"},
    {"topic": "Simple words", "en": "worthy", "ru": "достойно"},
    {"topic": "Simple words", "en": "count", "ru": "считать"},
    {"topic": "Simple words", "en": "violin", "ru": "скрипка"},
    {
        "topic": "Simple words",
        "en": "kind",
        "ru": "добрый, любезный также он может быть такими словами как: тип, разновидность, какой, вроде, приставка -то",
    },
    {"topic": "Simple words", "en": "bust", "ru": "банкротство или рвут"},
    {"topic": "Simple words", "en": "tear", "ru": "рвать"},
    {"topic": "Simple words", "en": "rip", "ru": "разрывать"},
    {"topic": "Simple words", "en": "serving", "ru": "приносить (в еде), порция"},
    {"topic": "Simple words", "en": "reason", "ru": "причина"},
    {"topic": "Simple words", "en": "fault", "ru": "вина"},
    {"topic": "Simple words", "en": "ain’t", "ru": "не"},
    {"topic": "Simple words", "en": "appear", "ru": "появляться"},
    {"topic": "Simple words", "en": "sign it", "ru": "подписать"},
    {"topic": "Simple words", "en": "vote", "ru": "голосовать"},
    {"topic": "Simple words", "en": "expect", "ru": "ожидать"},
    {"topic": "Simple words", "en": "rent", "ru": "аренда"},
    {"topic": "Simple words", "en": "convince", "ru": "убедить, убеждать"},
    {"topic": "Simple words", "en": "rambler", "ru": "бродяга, чесать языком, болтуны"},
    {"topic": "Simple words", "en": "ramble", "ru": "выдвигаться"},
    {"topic": "Simple words", "en": "cheap", "ru": "жадный, дешевый"},
    # Thanksgiving: история
    {"topic": "Thanksgiving: история", "en": "Thanksgiving", "ru": "история (тема)"},
    {
        "topic": "Thanksgiving: история",
        "en": "Plymouth",
        "ru": "Плимут — место (колония)",
    },
    {
        "topic": "Thanksgiving: история",
        "en": "Massachusetts",
        "ru": "Массачусетс — штат США",
    },
    {"topic": "Thanksgiving: история", "en": "settlers", "ru": "поселенцы — колонисты"},
    {
        "topic": "Thanksgiving: история",
        "en": "native",
        "ru": "коренной; местный — коренные народы",
    },
    {"topic": "Thanksgiving: история", "en": "harvest", "ru": "урожай — сбор урожая"},
    {
        "topic": "Thanksgiving: история",
        "en": "held",
        "ru": "проводился/состоялся — событие",
    },
    {
        "topic": "Thanksgiving: история",
        "en": "origins",
        "ru": "истоки/происхождение — история",
    },
    {
        "topic": "Thanksgiving: история",
        "en": "developed",
        "ru": "развился/сформировался — традиция",
    },
    {
        "topic": "Thanksgiving: история",
        "en": "secular",
        "ru": "светский — не религиозный",
    },
    {
        "topic": "Thanksgiving: история",
        "en": "prayer",
        "ru": "молитва — религиозная часть",
    },
    {
        "topic": "Thanksgiving: история",
        "en": "feasting",
        "ru": "пиршество/застолье — праздник",
    },
    {
        "topic": "Thanksgiving: история",
        "en": "occasion",
        "ru": "повод/событие — праздник",
    },
    # Thanksgiving: смысл и атмосфера
    {
        "topic": "Thanksgiving: смысл и атмосфера",
        "en": "gratitude",
        "ru": "благодарность — идея праздника",
    },
    {
        "topic": "Thanksgiving: смысл и атмосфера",
        "en": "grateful",
        "ru": "благодарный — чувство",
    },
    {
        "topic": "Thanksgiving: смысл и атмосфера",
        "en": "gather",
        "ru": "собираться — семья/друзья",
    },
    {
        "topic": "Thanksgiving: смысл и атмосфера",
        "en": "household",
        "ru": "дом/семья — традиции дома",
    },
    {
        "topic": "Thanksgiving: смысл и атмосфера",
        "en": "seated",
        "ru": "рассажены/сидят — за столом",
    },
    {
        "topic": "Thanksgiving: смысл и атмосфера",
        "en": "meal",
        "ru": "трапеза — праздничный ужин",
    },
    {
        "topic": "Thanksgiving: смысл и атмосфера",
        "en": "cheer",
        "ru": "веселье/радость — атмосфера",
    },
    {
        "topic": "Thanksgiving: смысл и атмосфера",
        "en": "festivities",
        "ru": "празднества — мероприятия",
    },
    {
        "topic": "Thanksgiving: смысл и атмосфера",
        "en": "broadcast nationwide",
        "ru": "транслируется по стране — ТВ/медиа",
    },
    {
        "topic": "Thanksgiving: смысл и атмосфера",
        "en": "traffic",
        "ru": "пробки/трафик — поездки",
    },
    {
        "topic": "Thanksgiving: смысл и атмосфера",
        "en": "extended",
        "ru": "продлённый/расширенный — длинные выходные",
    },
    # Thanksgiving: еда и традиции
    {
        "topic": "Thanksgiving: еда и традиции",
        "en": "includes",
        "ru": "включает — состав меню",
    },
    {
        "topic": "Thanksgiving: еда и традиции",
        "en": "roast",
        "ru": "жаркое/запечённое — блюдо",
    },
    {
        "topic": "Thanksgiving: еда и традиции",
        "en": "mashed",
        "ru": "пюре; «толчёный» — еда",
    },
    {
        "topic": "Thanksgiving: еда и традиции",
        "en": "pecan pies",
        "ru": "пироги с пеканом — десерт",
    },
    {
        "topic": "Thanksgiving: еда и традиции",
        "en": "own recipes",
        "ru": "свои рецепты — семейная кухня",
    },
    {
        "topic": "Thanksgiving: еда и традиции",
        "en": "mascot",
        "ru": "талисман/символ — индейка",
    },
    {
        "topic": "Thanksgiving: еда и традиции",
        "en": "recently",
        "ru": "недавно — в последние годы",
    },
    {
        "topic": "Thanksgiving: еда и традиции",
        "en": "evolved",
        "ru": "эволюционировал/изменился — традиция",
    },
    {
        "topic": "Thanksgiving: еда и традиции",
        "en": "humorous",
        "ru": "шутливый — церемония",
    },
    {
        "topic": "Thanksgiving: еда и традиции",
        "en": "two turkeys",
        "ru": "две индейки — церемония",
    },
    # Black Friday: покупки и деньги
    {
        "topic": "Black Friday: покупки и деньги",
        "en": "bargains",
        "ru": "выгодные покупки/скидки — распродажи",
    },
    {
        "topic": "Black Friday: покупки и деньги",
        "en": "consumers",
        "ru": "потребители — покупатели",
    },
    {
        "topic": "Black Friday: покупки и деньги",
        "en": "retailers",
        "ru": "ритейлеры/продавцы — магазины",
    },
    {
        "topic": "Black Friday: покупки и деньги",
        "en": "offer",
        "ru": "предлагать/предложение — скидки",
    },
    {
        "topic": "Black Friday: покупки и деньги",
        "en": "spending",
        "ru": "траты/расходы — деньги",
    },
    {
        "topic": "Black Friday: покупки и деньги",
        "en": "afford",
        "ru": "позволить себе — по бюджету",
    },
    {
        "topic": "Black Friday: покупки и деньги",
        "en": "consumerism",
        "ru": "потребительство — явление",
    },
    {
        "topic": "Black Friday: покупки и деньги",
        "en": "decisions",
        "ru": "решения — что покупать",
    },
    {
        "topic": "Black Friday: покупки и деньги",
        "en": "encourages",
        "ru": "побуждает/поощряет — призыв",
    },
    {
        "topic": "Black Friday: покупки и деньги",
        "en": "encourage",
        "ru": "побуждать/поощрять — призыв",
    },
    {
        "topic": "Black Friday: покупки и деньги",
        "en": "aims to raise",
        "ru": "стремится повысить — цель кампании",
    },
    {
        "topic": "Black Friday: покупки и деньги",
        "en": "awareness",
        "ru": "осведомлённость — о влиянии",
    },
    {
        "topic": "Black Friday: покупки и деньги",
        "en": "avoid",
        "ru": "избегать — не покупать лишнее",
    },
    {
        "topic": "Black Friday: покупки и деньги",
        "en": "thrown",
        "ru": "выкинутый/брошенный — мусор",
    },
    {
        "topic": "Black Friday: покупки и деньги",
        "en": "thrown away",
        "ru": "выброшенный — отходы",
    },
    # Служебные слова
    {"topic": "Служебные слова", "en": "several", "ru": "несколько — количество"},
    {"topic": "Служебные слова", "en": "preparation", "ru": "подготовка — процесс"},
    {
        "topic": "Служебные слова",
        "en": "combines",
        "ru": "объединяет/сочетает — про традиции",
    },
    {"topic": "Служебные слова", "en": "although", "ru": "хотя — противопоставление"},
    {"topic": "Служебные слова", "en": "largely", "ru": "в основном — уточнение"},
    {
        "topic": "Служебные слова",
        "en": "primarily",
        "ru": "главным образом — уточнение",
    },
    {"topic": "Служебные слова", "en": "instead", "ru": "вместо этого — замена"},
    {"topic": "Служебные слова", "en": "opportunity", "ru": "возможность — шанс"},
    {"topic": "Служебные слова", "en": "spread", "ru": "распространять(ся) — процесс"},
    {
        "topic": "Служебные слова",
        "en": "spreading",
        "ru": "распространяющийся/распространение — процесс",
    },
    {"topic": "Служебные слова", "en": "through", "ru": "через/посредством — связь"},
    {"topic": "Служебные слова", "en": "throughout", "ru": "по всему — охват"},
    {"topic": "Служебные слова", "en": "earlier", "ru": "раньше — время"},
    {"topic": "Служебные слова", "en": "growing", "ru": "растущий — тренд"},
    {"topic": "Служебные слова", "en": "expected", "ru": "ожидаемый — ожидания"},
    {
        "topic": "Служебные слова",
        "en": "beyond",
        "ru": "сверх/за пределами — «больше чем»",
    },
    {"topic": "Служебные слова", "en": "carry", "ru": "нести/переносить — действие"},
    {
        "topic": "Служебные слова",
        "en": "carry out",
        "ru": "выполнять/осуществлять — действие/план",
    },
    {"topic": "Служебные слова", "en": "desperately", "ru": "отчаянно — эмоция"},
    {"topic": "Служебные слова", "en": "letter", "ru": "письмо — сообщение"},
]
